"""Generate Japanese and printable ASCII glyphs with a shared 16px height."""
import gzip
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/unifont-jp.hex.gz"
EXPECTED = "ecf9455c8a44b09e3f645e6b1bab4ac22a57399bf19b1f8e950e11af9523df8c"


def main():
    if hashlib.sha256(SOURCE.read_bytes()).hexdigest() != EXPECTED:
        raise ValueError("Unifont source checksum mismatch")
    text = (ROOT / "include/ui-text.h").read_text(encoding="utf-8")
    needed = {ord(c) for c in text if ord(c) > 127} | set(range(32, 127))
    glyphs = {}
    for line in gzip.decompress(SOURCE.read_bytes()).decode("ascii").splitlines():
        code, bitmap = line.split(":")
        point = int(code, 16)
        if point in needed:
            data = bytes.fromhex(bitmap)
            if len(data) != (16 if point < 128 else 32):
                raise ValueError(f"Unexpected glyph dimensions: {point:04X}")
            glyphs[point] = data
    if needed - glyphs.keys():
        raise ValueError(f"Missing glyphs: {needed - glyphs.keys()}")
    lines = ["// Generated by scripts/generate-font.py; do not edit.",
             "// Unifont JP 17.0.05 subset, SIL OFL 1.1; see licenses/.",
             "#pragma once", "#include <stdint.h>", "namespace povo {",
             "struct Glyph { uint16_t codepoint; uint8_t bitmap[32]; };",
             "constexpr Glyph kJapaneseGlyphs[] = {"]
    for point, data in sorted(glyphs.items()):
        if point < 128:
            continue
        lines.append("  {0x%04X, {%s}}," % (point, ",".join(f"0x{v:02X}" for v in data)))
    lines += ["};", "constexpr uint8_t kAsciiGlyphs[95][16] = {"]
    for point in range(32, 127):
        lines.append("  {%s}," % ",".join(f"0x{v:02X}" for v in glyphs[point]))
    lines += ["};", "}  // namespace povo", ""]
    (ROOT / "include/japanese-font.h").write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(glyphs) - 95} Japanese and 95 ASCII glyphs (16px high)")


if __name__ == "__main__":
    main()
