"""Refresh the public root from an OS-verified app.povo.jp TLS chain (Python 3.13+)."""
from pathlib import Path
import socket
import ssl
import hashlib

context = ssl.create_default_context()
with socket.create_connection(("app.povo.jp", 443), timeout=15) as tcp:
    with context.wrap_socket(tcp, server_hostname="app.povo.jp") as tls:
        root = tls.get_verified_chain()[-1]
pem = ssl.DER_cert_to_PEM_cert(root)
destination = Path(__file__).parents[1] / "include" / "povo-root-ca.h"
destination.write_text(
    '#pragma once\n// Generated by scripts/update-povo-ca.py from an OS-verified TLS chain.\n'
    'namespace povo {\nconstexpr const char* rootCa = R"PEM(' + pem + ')PEM";\n}\n',
    encoding="utf-8",
)
print("Public root SHA-256:", hashlib.sha256(root).hexdigest())
