#pragma once
namespace povo { namespace text {
constexpr const char* title = "povo トッピング";
constexpr const char* unknown = "不明";
constexpr const char* sources[] = {"不明", "公式取得"};
constexpr const char* pending = "更新確認待ち";
constexpr const char* remaining = "残り %llu日 %llu時間";
constexpr const char* minutes = "%llu時間 %llu分";
constexpr const char* expiry = "期限 ";
constexpr const char* sync = "最終同期 %llu分前";
constexpr const char* stale = "同期停止・古い情報";
constexpr const char* noStatus = "状態を待っています";
constexpr const char* configuring = "設定不足: device-config.h";
constexpr const char* wifi = "Wi-Fi接続待ち";
constexpr const char* clock = "時刻同期待ち・NTP確認";
constexpr const char* connection = "通信失敗・接続と証明書確認";
constexpr const char* unauthorized = "要ログイン・設定用Wi-Fiへ";
constexpr const char* unavailable = "公式APIの応答を確認";
constexpr const char* invalid = "応答異常・API形式を確認";
constexpr const char* directMode = "公式APIへ直接接続";
constexpr const char* precision = "期限の表示精度: 分";
constexpr const char* setupTitle = "スマホでログイン設定";
constexpr const char* setupWifi = "次のWi-Fiに接続";
constexpr const char* setupOpen = "接続後ブラウザで開く";
constexpr const char* portalError = "設定用Wi-Fiの起動失敗";
constexpr const char* storageError = "認証の保存領域を確認";
constexpr const char* tabStatus = "表示";
constexpr const char* tabSleep = "自動消灯";
constexpr const char* sleepTitle = "自動消灯設定";
constexpr const char* sleepNow = "現在";
constexpr const char* sleepSelect = "タッチで選択";
constexpr const char* sleepPrev = "前へ";
constexpr const char* sleepNext = "次へ";
constexpr const char* sleepNone = "なし";
constexpr const char* sleepSecUnit = "秒";
constexpr const char* sleepMinUnit = "分";
constexpr const char* sleepHourUnit = "時間";
constexpr const char* rotateHint = "BOOT1回で画面反転";
} }
